/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.awt.Color;

/**
 *
 * @author osmas
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttsave = new javax.swing.JButton();
        butthelp = new javax.swing.JButton();
        buttclear = new javax.swing.JButton();
        buttexit = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblgen = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        lblsur = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lblcont = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtsur = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtcont = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        other = new javax.swing.JRadioButton();
        llbname = new javax.swing.JLabel();
        llbsur = new javax.swing.JLabel();
        llbid = new javax.swing.JLabel();
        llbdob = new javax.swing.JLabel();
        llbgen = new javax.swing.JLabel();
        llbcont = new javax.swing.JLabel();
        llbemail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        buttsave.setText("SAVE");
        buttsave.addActionListener(this::buttsaveActionPerformed);

        butthelp.setText("HELP");
        butthelp.addActionListener(this::butthelpActionPerformed);

        buttclear.setText("CLEAR");
        buttclear.addActionListener(this::buttclearActionPerformed);

        buttexit.setText("EXIT");
        buttexit.addActionListener(this::buttexitActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttexit)
                    .addComponent(buttclear)
                    .addComponent(butthelp)
                    .addComponent(buttsave))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(buttsave)
                .addGap(40, 40, 40)
                .addComponent(buttclear)
                .addGap(39, 39, 39)
                .addComponent(butthelp)
                .addGap(40, 40, 40)
                .addComponent(buttexit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblname.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("NAME:");

        lblid.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblid.setForeground(new java.awt.Color(255, 255, 255));
        lblid.setText("ID/STUDENT NO:");

        lblgen.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblgen.setForeground(new java.awt.Color(255, 255, 255));
        lblgen.setText("GENDER:");

        txtname.addActionListener(this::txtnameActionPerformed);

        txtid.addActionListener(this::txtidActionPerformed);

        male.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("MALE");

        female.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("FEMALE");

        lblsur.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblsur.setForeground(new java.awt.Color(255, 255, 255));
        lblsur.setText("SURNAME:");

        lbldob.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbldob.setForeground(new java.awt.Color(255, 255, 255));
        lbldob.setText("DATE OF BIRTH:");

        lblcont.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblcont.setForeground(new java.awt.Color(255, 255, 255));
        lblcont.setText("CONTACT NO:");

        lblemail.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblemail.setForeground(new java.awt.Color(255, 255, 255));
        lblemail.setText("EMAIL:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setText("DATA VAIDATION SYSTEM");

        other.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        other.setForeground(new java.awt.Color(255, 255, 255));
        other.setText("OTHER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(llbname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(llbsur))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(llbid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(llbdob)))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblgen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(llbgen, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(other)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(llbcont)
                                        .addGap(65, 65, 65))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(male)
                                                .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                .addComponent(txtid))
                                            .addComponent(female))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbldob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblsur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblcont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtsur, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                    .addComponent(txtcont)
                                                    .addComponent(txtemail)
                                                    .addComponent(llbemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(217, 217, 217))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsur)
                            .addComponent(txtsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llbname)
                            .addComponent(llbsur))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldob)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llbid)
                            .addComponent(llbdob))
                        .addGap(43, 43, 43)
                        .addComponent(male)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcont)
                            .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(female)
                            .addComponent(lblgen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(other)
                            .addComponent(llbcont))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblemail)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(llbemail)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(llbgen)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttsaveActionPerformed
        // TODO add your handling code here:
        String Name = txtname.getText().trim();
        String Surname = txtsur.getText().trim();
        String ID = txtid.getText().trim();
        String DobText = txtdob.getText().trim();
        String Contact = txtcont.getText().trim();
        String Email = txtemail.getText().trim();

        boolean isValid = true;

        //1. Name - Presence + Type
        if(Name.isEmpty()){
            llbname.setForeground(Color.red);
            llbname.setText("Name Cannot Be Empty!");
            isValid = false;
        }else if(!Name.matches("[A-Z,a-z]+")){
            llbname.setForeground(Color.red);
            llbname.setText("Letters Only!");
            isValid = false;
        }

        if(Surname.isEmpty()){
            llbsur.setForeground(Color.red);
            llbsur.setText("Surname Cannot Be Empty!");
            isValid = false;
        }else if(!Surname.matches("[A-Z,a-z]+")){
            llbsur.setForeground(Color.red);
            llbsur.setText("Letters Only!");
            isValid = false;
            llbsur.setForeground(Color.red);
        }

        if(ID.isEmpty()){
            llbid.setForeground(Color.red);
            llbid.setText("ID Cannot Be Empty!");
            isValid = false;
        }else if(!Surname.matches("\\d+")){
            llbid.setForeground(Color.red);
            llbid.setText("Must Be Digits Only!");
            isValid = false;
        }else if(ID.length() !=13){
            llbid.setForeground(Color.red);
            llbid.setText("ID Must Be Exactly 13 Characters!");
            isValid = false;
        }

        if(DobText.isEmpty()){
            llbdob.setForeground(Color.red);
            llbdob.setText("DOB Cannot Be Empty!");
            isValid = false;
        }else{
            try{
                int dob = Integer.parseInt(DobText);
                if(dob < 6 || dob > 100){
                    llbdob.setForeground(Color.red);
                    llbdob.setText("Must Be 18 - 100.");
                }
            }catch(NumberFormatException e){
                llbdob.setForeground(Color.red);
                llbdob.setText("DOB Must Be A Number!");
                isValid = false;
            }
        }
        if(!male.isSelected() && !female.isSelected() && !other.isSelected()){
            llbgen.setForeground(Color.red);
            llbgen.setText("Gender Cannot Be Empty!");
            isValid = false;
        }

        if(Contact.isEmpty()){
            llbcont.setForeground(Color.red);
            llbcont.setText("Contact Cannot Be Empty!");
            isValid = false;
        }else if(!Contact.matches("\\d{10}")){
            llbcont.setForeground(Color.red);
            llbcont.setText("Must Be Exactly 10 Digits!");
            isValid = false;
        }

        if(Email.isEmpty()){
            llbemail.setForeground(Color.red);
            llbemail.setText("Email Cannot Be Empty!");
            isValid = false;
        }else if(!Email.matches("@")){
            llbemail.setForeground(Color.red);
            llbemail.setText("Invalid Email Format!");
            isValid = false;
        }

    }//GEN-LAST:event_buttsaveActionPerformed

    private void butthelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butthelpActionPerformed

    private void buttclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttclearActionPerformed
        // TODO add your handling code here:
        txtname.setText("");
        txtsur.setText("");
        txtid.setText("");
        txtdob.setText("");
        txtcont.setText("");
        txtemail.setText("");
        male.setSelected(false);
        female.setSelected(false);
        other.setSelected(false);

        llbname.setText("");
        llbsur.setText("");
        llbid.setText("");
        llbcont.setText("");
        llbdob.setText("");
        llbemail.setText("");
        llbgen.setText("");
    }//GEN-LAST:event_buttclearActionPerformed

    private void buttexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttexitActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed

    }//GEN-LAST:event_txtnameActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttclear;
    private javax.swing.JButton buttexit;
    private javax.swing.JButton butthelp;
    private javax.swing.JButton buttsave;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcont;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblgen;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblsur;
    private javax.swing.JLabel llbcont;
    private javax.swing.JLabel llbdob;
    private javax.swing.JLabel llbemail;
    private javax.swing.JLabel llbgen;
    private javax.swing.JLabel llbid;
    private javax.swing.JLabel llbname;
    private javax.swing.JLabel llbsur;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton other;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsur;
    // End of variables declaration//GEN-END:variables
}
